In [3]:
UDEPREL = Dict{String,Int8}(
"root"       => 1,  # root
"acl"        => 2,  # clausal modifier of noun (adjectival clause)
"advcl"      => 3,  # adverbial clause modifier
"advmod"     => 4,  # adverbial modifier
"amod"       => 5,  # adjectival modifier
"appos"      => 6,  # appositional modifier
"aux"        => 7,  # auxiliary
"case"       => 8,  # case marking
"cc"         => 9,  # coordinating conjunction
"ccomp"      => 10, # clausal complement
"clf"        => 11, # classifier
"compound"   => 12, # compound
"conj"       => 13, # conjunct
"cop"        => 14, # copula
"csubj"      => 15, # clausal subject
"dep"        => 16, # unspecified dependency
"det"        => 17, # determiner
"discourse"  => 18, # discourse element
"dislocated" => 19, # dislocated elements
"expl"       => 20, # expletive
"fixed"      => 21, # fixed multiword expression
"flat"       => 22, # flat multiword expression
"goeswith"   => 23, # goes with
"iobj"       => 24, # indirect object
"list"       => 25, # list
"mark"       => 26, # marker
"nmod"       => 27, # nominal modifier
"nsubj"      => 28, # nominal subject
"nummod"     => 29, # numeric modifier
"obj"        => 30, # object
"obl"        => 31, # oblique nominal
"orphan"     => 32, # orphan
"parataxis"  => 33, # parataxis
"punct"      => 34, # punctuation
"reparandum" => 35, # overridden disfluency
"vocative"   => 36, # vocative
"xcomp"      => 37, # open clausal complement
)

Dict{String,Int8} with 37 entries:
  "reparandum" => 35
  "root"       => 1
  "vocative"   => 36
  "csubj"      => 15
  "advmod"     => 4
  "expl"       => 20
  "iobj"       => 24
  "mark"       => 26
  "advcl"      => 3
  "nmod"       => 27
  "parataxis"  => 33
  "orphan"     => 32
  "nsubj"      => 28
  "discourse"  => 18
  "dep"        => 16
  "appos"      => 6
  "ccomp"      => 10
  "conj"       => 13
  "goeswith"   => 23
  "list"       => 25
  "xcomp"      => 37
  "amod"       => 5
  "aux"        => 7
  "acl"        => 2
  "case"       => 8
  ⋮            => ⋮

In [13]:
function load_data3(path, UDEPREL)
    xtrain, ytrain, deprels = open(path) do f
    xtrain = []
    ytrain = []
    deprels = []
    sentence = []
    temprels = []
    arcs = []
    count = 1
    for i in enumerate(eachline(f))  
      if i[2] == ""
        push!(xtrain, sentence)
        labels = zeros(count, count)
        push!(ytrain, arcs)
        push!(deprels, temprels)
      elseif i[2][1] != '#'
        temp = split(i[2])
        if temp[1] == "1"
            sentence = []
            arcs = []
            temprels = []
            push!(sentence, temp[2])
            push!(arcs, parse(Int64, temp[7]))
            tmp = split(temp[8], ":")
            push!(temprels, UDEPREL[lowercase(tmp[1])])
            count = 1
        else
            if isnumeric(temp[7][1])
                push!(sentence, temp[2]) 
                tmp = split(temp[8], ":")
                push!(temprels, UDEPREL[lowercase(tmp[1])])
                push!(arcs, parse(Int64, temp[7]))
            end
            count += 1
        end
      end
    end
    xtrain, ytrain, deprels
    end
    xtrain, ytrain, deprels
end

load_data3 (generic function with 1 method)

In [14]:
xt, yt, anan = load_data3("en_ewt-ud-train.conllu", UDEPREL)

(Any[Any["Al", "-", "Zaman", ":", "American", "forces", "killed", "Shaikh", "Abdullah", "al"  …  "the", "town", "of", "Qaim", ",", "near", "the", "Syrian", "border", "."], Any["[", "This", "killing", "of", "a", "respected", "cleric", "will", "be", "causing", "us", "trouble", "for", "years", "to", "come", ".", "]"], Any["DPA", ":", "Iraqi", "authorities", "announced", "that", "they", "had", "busted", "up", "3", "terrorist", "cells", "operating", "in", "Baghdad", "."], Any["Two", "of", "them", "were", "being", "run", "by", "2", "officials", "of", "the", "Ministry", "of", "the", "Interior", "!"], Any["The", "MoI", "in", "Iraq", "is", "equivalent", "to", "the", "US", "FBI"  …  "members", "of", "the", "Weathermen", "bombers", "back", "in", "the", "1960s", "."], Any["The", "third", "was", "being", "run", "by", "the", "head", "of", "an", "investment", "firm", "."], Any["You", "wonder", "if", "he", "was", "manipulating", "the", "market", "with", "his", "bombing", "targets", "."], Any["The", "c

In [15]:
anan

12543-element Array{Any,1}:
 Any[1, 34, 22, 34, 5, 28, 33, 30, 22, 22  …  17, 27, 8, 27, 34, 8, 17, 5, 27, 34]
 Any[34, 17, 28, 8, 17, 5, 27, 7, 7, 1, 24, 30, 8, 31, 26, 2, 34, 34]             
 Any[1, 34, 5, 28, 33, 26, 28, 7, 10, 12, 29, 5, 30, 2, 8, 31, 34]                
 Any[28, 8, 27, 7, 7, 1, 8, 29, 31, 8, 17, 27, 8, 17, 27, 34]                     
 Any[17, 28, 8, 27, 14, 1, 8, 17, 12, 31  …  30, 8, 17, 12, 27, 4, 8, 17, 31, 34] 
 Any[17, 28, 7, 7, 1, 8, 17, 31, 8, 17, 12, 27, 34]                               
 Any[28, 1, 26, 28, 7, 10, 17, 30, 8, 27, 12, 31, 34]                             
 Any[17, 28, 7, 1, 8, 17, 12, 9, 12, 34, 13, 31, 8, 17, 27, 34]                   
 Any[26, 17, 28, 7, 4, 3, 26, 37, 30, 26  …  28, 2, 26, 37, 17, 5, 30, 4, 37, 34] 
 Any[28, 1, 30, 4, 4, 8, 17, 12, 31, 28, 7, 4, 2, 8, 17, 5, 31, 8, 31, 34]        
 Any[1, 34, 22, 34, 28, 33, 17, 30, 8, 17, 12, 12, 27, 26, 3, 30, 8, 31, 34]      
 Any[17, 12, 28, 8, 12, 27, 1, 26, 28, 7  …  3, 17, 5, 28, 

In [16]:
haha = sort(collect(keys(UDEPREL)))
lala = haha[1:34]
temp = Array{String, 1}()
push!(temp, "root")
append!(temp, lala)
append!(temp, haha[36:37])

37-element Array{String,1}:
 "root"      
 "acl"       
 "advcl"     
 "advmod"    
 "amod"      
 "appos"     
 "aux"       
 "case"      
 "cc"        
 "ccomp"     
 "clf"       
 "compound"  
 "conj"      
 ⋮           
 "mark"      
 "nmod"      
 "nsubj"     
 "nummod"    
 "obj"       
 "obl"       
 "orphan"    
 "parataxis" 
 "punct"     
 "reparandum"
 "vocative"  
 "xcomp"     

In [17]:
actcount = 0
index = 1
for lol in yt
    count = 0
   for i in lol
       if i == 0
            count=count+1
        end
    end
    if count >= 2
        println(index)
       actcount = actcount+1
    end
    index = index + 1
end
println(actcount)

0


In [18]:
yt[62]

13-element Array{Any,1}:
  2
  3
  5
  5
  0
  5
  8
  5
  8
 11
  5
 11
  5